/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.techtrek.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author moset
 */
public class WelcomePage extends javax.swing.JPanel implements ActionListener {
    Frame frame;
    /**
     * Creates new form welcomePage
     * @param frame
     */
    public WelcomePage(Frame frame) {
        this.frame = frame;
        initComponents();
        eventListeners();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome_gameTitle = new javax.swing.JLabel();
        welcome_instructions = new javax.swing.JLabel();
        welcome_easyModeBtn = new javax.swing.JButton();
        welcome_mediumModeBtn = new javax.swing.JButton();
        welcome_hardModeBtn = new javax.swing.JButton();

        welcome_gameTitle.setFont(new java.awt.Font("Segoe UI", 0, 56)); // NOI18N
        welcome_gameTitle.setText("Minesweeper");

        welcome_instructions.setText("Select Game Difficulty");

        welcome_easyModeBtn.setText("Easy");

        welcome_mediumModeBtn.setText("Medium");
        welcome_mediumModeBtn.setMinimumSize(new java.awt.Dimension(72, 23));

        welcome_hardModeBtn.setText("Hard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(welcome_gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(welcome_instructions))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcome_easyModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcome_mediumModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(welcome_hardModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(welcome_gameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcome_instructions, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(welcome_easyModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(welcome_mediumModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(welcome_hardModeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton welcome_easyModeBtn;
    private javax.swing.JLabel welcome_gameTitle;
    private javax.swing.JButton welcome_hardModeBtn;
    private javax.swing.JLabel welcome_instructions;
    private javax.swing.JButton welcome_mediumModeBtn;
    // End of variables declaration//GEN-END:variables

    private void eventListeners() {
       JButton buttonGroup[] = { welcome_easyModeBtn, welcome_mediumModeBtn, welcome_hardModeBtn};
       for(JButton button : buttonGroup) {
           button.addActionListener(this);
       }
    }
    
    @Override
    public void actionPerformed(ActionEvent buttonClick) {

        //TODO add the variables that will be sent as 
        //arguements for each game mode
        if(buttonClick.getSource() == welcome_easyModeBtn) {
            frame.switchPanel(new GameWindow(frame));
            
        } else if (buttonClick.getSource() == welcome_mediumModeBtn) {
            frame.switchPanel(new GameWindow(frame));
            
        } else if (buttonClick.getSource() == welcome_hardModeBtn) {
            frame.switchPanel(new GameWindow(frame));
            
        }
    }
}
